[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "docx>=0.2.4",
    "edge-tts>=7.0.2",
    "flask>=3.1.1",
    "gtts>=2.5.4",
    "pydub>=0.25.1",
    "werkzeug>=3.1.3",
]
